//! Key-value store contract conformance for the Axum adapter.
//!
//! `EdgeZero` ships `key_value_store_contract_tests!`, a suite every
//! `KvStore` implementation is expected to satisfy: put and get, missing
//! keys, overwrite, delete, delete of a key that is not there, existence,
//! time-to-live storage, time-to-live expiry, paging, and prefix filtering.
//!
//! The factory below builds the store through
//! [`trusted_server_adapter_axum::platform::open_kv_store`], the same entry
//! point the running server uses, so a green run is evidence about the store
//! this adapter actually injects rather than about `PersistentKvStore` in the
//! abstract.

// The assertions below are generated by EdgeZero's
// `key_value_store_contract_tests!` macro, which uses `unwrap()` throughout.
// The workspace denies `unwrap_used`, so the generated code needs an
// allowance here rather than a rewrite of a shared upstream macro.
#![allow(clippy::unwrap_used)]

use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use trusted_server_adapter_axum::platform::open_kv_store;
use trusted_server_core::platform::PlatformKvStore;

/// Counter making each store file unique within a run.
static NEXT_STORE: AtomicU64 = AtomicU64::new(0);

/// Returns a database path no other test in this run will open.
///
/// `redb` takes an exclusive file lock, so two tests sharing a path would
/// fail on the lock rather than on the behavior under test. Each test also
/// needs an empty store, because the suite asserts that a key is absent
/// before writing it.
fn fresh_store_path() -> PathBuf {
    let sequence = NEXT_STORE.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir()
        .join(format!("trusted-server-kv-contract-{}", std::process::id()))
        .join(format!("store-{sequence}.redb"))
}

/// Opens a fresh store through the adapter's own wiring.
fn fresh_store() -> Arc<dyn PlatformKvStore> {
    let path = fresh_store_path();
    // A previous run that was killed can leave the file behind, and a
    // populated store would fail the suite's "key is absent" assertions.
    let _ = std::fs::remove_file(&path);
    open_kv_store(&path).expect("should open a temporary KV store")
}

edgezero_core::key_value_store_contract_tests!(axum_kv_contract, fresh_store());
