// Strips lines whose first non-whitespace token is `//`.
//
// Known limitations (both produce false positives, never false negatives):
// - String literals: `"fastly::Request"` in a test assertion would trigger a
//   spurious failure even though it is not a real Fastly dependency.
// - Block comments: `/* fastly::Request */` is not stripped. A banned pattern
//   inside a block comment causes a spurious failure; one hidden *outside* a
//   block comment is still caught by the non-comment portions of the line.
//
// False positives are safe for a guard test — they cause a noisy failure that
// forces investigation rather than letting a real regression slip through
// silently. False negatives are not possible with the current banned-pattern
// list because none of the migrated files use block comments in practice.
fn strip_line_comments(source: &str) -> String {
    source
        .lines()
        .filter(|line| {
            let trimmed = line.trim_start();
            !trimmed.starts_with("//")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn fastly_sdk_pattern() -> regex::Regex {
    regex::Regex::new(r"\b(?:use\s+fastly\b|fastly::)")
        .expect("should compile migration guard regex")
}

// The list of files this guard checks is generated by `build.rs` from every
// `.rs` file under `src`, so a file added to core joins the guard on its own
// and a file that leaves core (a vendor integration moving to its own crate,
// for instance) leaves the guard without anyone editing this file. The
// generated file defines `CHECKED_SOURCES`.
//
// `migration_guards.rs` itself is left out, because the banned pattern appears
// here as the regex literal the guard matches with.
include!(concat!(env!("OUT_DIR"), "/migration_guard_sources.rs"));

fn checked_sources() -> &'static [(&'static str, &'static str)] {
    CHECKED_SOURCES
}

#[test]
fn core_modules_do_not_reference_the_fastly_sdk() {
    let banned = fastly_sdk_pattern();

    for &(path, source) in checked_sources() {
        let uncommented = strip_line_comments(source);
        assert!(
            !banned.is_match(&uncommented),
            "{path} should not reference the Fastly SDK — core is platform-agnostic"
        );
    }
}

/// A generation bug that produced an empty or truncated list would leave the
/// guard above passing while checking nothing, so this pins the list to the
/// tree it is meant to cover.
#[test]
fn the_generated_list_covers_the_crate() {
    let sources = checked_sources();

    assert!(
        sources.len() > 100,
        "should check every core source file, found {}",
        sources.len()
    );
    assert!(
        sources.iter().any(|&(path, _)| path == "lib.rs"),
        "should check the crate root"
    );
    assert!(
        sources
            .iter()
            .any(|&(path, _)| path == "integrations/registry.rs"),
        "should check files in subdirectories"
    );
    assert!(
        !sources
            .iter()
            .any(|&(path, _)| path == "migration_guards.rs"),
        "should leave out the guard's own source, which holds the banned pattern"
    );
}
